adding member sign up
devedmonton/devedmonton.com pull request #135
Opened 2021-11-30 22:27 UTC by MandyMeindersma

Finally finishing my pr from like months ago.

2021-11-30 22:28 UTC, MandyMeindersma commented on pages/become_a_member.vue
> +                about when your membership expires, these can be answered from
Last pr we were worried about the wording of this, so I am hoping just saying refer to the bylaws will hopefully get us through :P

2021-11-30 22:29 UTC, MarkBennett commented
Just taking a quick look at this. It's saying you need to update from the main branch.

2021-11-30 22:36 UTC, MandyMeindersma commented
> Just taking a quick look at this. It's saying you need to update from the main branch.

I mean yeah, I am missing a commit from the all contributors but that shouldn't affect what I am doing.

2021-12-06 05:42 UTC, MandyMeindersma commented
@MarkBennett updated now

2021-12-06 19:35 UTC, MarkBennett commented
> @MarkBennett updated now

Awesome. I'll check it out @MandyMeindersma! :)

2021-12-06 19:39 UTC, MarkBennett requested changes
Looks great @MandyMeindersma. I like that this is up in one place that we can send interested people to now, and that it will explain why they might not want to become a member.

One small suggestion to add a link to the bylaws, then I'll sign off.

2021-12-06 19:39 UTC, MarkBennett commented on pages/become_a_member.vue
> +                the bylaws.
```suggestion
               <a href="https://docs.google.com/document/d/1i6oXabir-628csa2bQacHpc17Kmhec9EfkyHij9yQGM/edit#heading=h.sns5qzyi4gru">the bylaws</a>.
```

2021-12-06 19:58 UTC, MandyMeindersma commented
@MarkBennett all finished 👍

2021-12-06 20:00 UTC, MarkBennett approved these changes
LGTM! Ship it! 🥳

2021-12-06 20:00 UTC, merged